import { useState } from 'react';
import { useSendTransaction, useAccount } from 'wagmi';
import { encodeWithBuilderCode, COLARY_ABI, COLARY_CONTRACT_ADDRESS } from '../lib/builderCode';

export function useRewards() {
  const { sendTransactionAsync } = useSendTransaction();
  const { isConnected } = useAccount();
  const [isClaiming, setIsClaiming] = useState(false);
  const [txHash, setTxHash] = useState<string | null>(null);

  const claimRewards = async (score: number) => {
    if (!isConnected) throw new Error("Wallet not connected");
    
    setIsClaiming(true);
    setTxHash(null);
    try {
      // In a real game, 'signature' would be generated by your backend
      // to verify the score is legit. We use a mock signature here.
      const mockSignature = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef';
      
      // We encode the ABI function data and append the ERC-8021 builder code
      const dataWithBuilderCode = encodeWithBuilderCode(
        COLARY_ABI, 
        'claimRewards', 
        [BigInt(score), mockSignature as `0x${string}`]
      );

      console.log('Sending transaction with builder code...', {
        to: COLARY_CONTRACT_ADDRESS,
        data: dataWithBuilderCode,
      });

      const hash = await sendTransactionAsync({
        to: COLARY_CONTRACT_ADDRESS as `0x${string}`,
        data: dataWithBuilderCode,
        // value: 0n, // Optional if it requires ETH
      });

      setTxHash(hash);
      return hash;
    } catch (err) {
      console.error("Failed to claim rewards:", err);
      throw err;
    } finally {
      setIsClaiming(false);
    }
  };

  return { claimRewards, isClaiming, txHash };
}
